(function(){
  'use strict';
  const A=window.JC_APP,$=id=>document.getElementById(id);const BUCKET='attendant-media';let access=null,step=1,currentSettings={},media={logo:null,assistant:null,assistantType:null};
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);}
  function normalizePhone(value){let n=String(value||'').replace(/\D/g,'');if((n.length===10||n.length===11)&&!n.startsWith('55'))n='55'+n;return n;}
  function inferType(value,provided){if(provided)return provided;const s=String(value||'').toLowerCase();return s.startsWith('data:video/')||/\.(mp4|webm)(\?|#|$)/.test(s)?'video':'image';}
  function mediaLabel(value){if(!value)return 'Não informada';return String(value).startsWith('data:')?'Arquivo local enviado':value;}
  function values(){const logo=media.logo===null?(currentSettings.logoUrl||''):media.logo,assistant=media.assistant===null?(currentSettings.assistantMedia||''):media.assistant,assistantType=media.assistant===null?(currentSettings.assistantMediaType||inferType(assistant)):media.assistantType;return{brand:$('brand').value.trim(),assistantName:$('assistantName').value.trim(),whatsapp:normalizePhone($('whatsapp').value),welcome:$('welcome').value.trim(),panelColor:$('panelColor').value||'#101c24',logoUrl:logo||'',assistantMedia:assistant||'',assistantMediaType:assistant?inferType(assistant,assistantType):'',pixKey:$('pixKey').value.trim(),pixReceiver:$('pixReceiver').value.trim(),pixBank:$('pixBank').value.trim()};}
  function validate(){const v=values();if(!v.brand)throw new Error('Preencha o nome da empresa ou marca.');if(!v.assistantName)throw new Error('Preencha o nome da atendente.');if(v.whatsapp.length<12||v.whatsapp.length>13)throw new Error('Digite o WhatsApp com DDD. Exemplo: 55997234936.');return v;}
  function setStep(n){step=n;document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));$('step1').classList.toggle('active',n===1);$('step2').classList.toggle('active',n===2);$('backBtn').style.visibility=n===1?'hidden':'visible';$('nextBtn').classList.toggle('hidden',n===2);$('submitBtn').classList.toggle('hidden',n!==2);if(n===2)renderReview();}
  function renderReview(){const v=validate(),rows=[['Empresa ou marca',v.brand],['Nome da atendente',v.assistantName],['WhatsApp',v.whatsapp],['Mensagem',v.welcome||'Mensagem atual/padrão'],['Logo',mediaLabel(v.logoUrl)],['Foto ou vídeo',mediaLabel(v.assistantMedia)],['Chave PIX',v.pixKey||'Não informada'],['Recebedor',v.pixReceiver||'Não informado'],['Banco',v.pixBank||'Não informado']];$('reviewList').innerHTML=rows.map(([a,b])=>`<div class="row"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');}
  function renderPreview(id,value,type,fallback){const box=$(id);if(!value){box.textContent=fallback;return;}box.innerHTML=type==='video'?`<video src="${esc(value)}" muted controls playsinline></video>`:`<img src="${esc(value)}" alt="Prévia">`;}
  async function readMediaFile(file,kind){if(!file)return null;const image=file.type.startsWith('image/'),video=file.type.startsWith('video/');if(kind==='logo'&&!image)throw new Error('A logo precisa ser uma imagem.');if(kind==='assistant'&&!image&&!video)throw new Error('Escolha uma imagem ou vídeo compatível.');const limit=video?5*1024*1024:2*1024*1024;if(file.size>limit)throw new Error(video?'O vídeo local deve ter no máximo 5 MB. Para vídeos maiores, use o link.':'A imagem local deve ter no máximo 2 MB. Para imagens maiores, use o link.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({value:String(reader.result||''),type:video?'video':'image'});reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file);});}
  function loadFields(s){currentSettings=s;media={logo:null,assistant:null,assistantType:null};$('brand').value=s.brand||access.profile.full_name||'';$('assistantName').value=s.assistantName||'Aline';$('whatsapp').value=s.whatsapp||access.profile.whatsapp||'';$('welcome').value=s.welcome||'Vou entender o que você procura, responder suas dúvidas e ajudar durante o atendimento.';$('panelColor').value=/^#[0-9a-f]{6}$/i.test(s.panelColor||'')?s.panelColor:'#101c24';$('pixKey').value=s.pixKey||'';$('pixReceiver').value=s.pixReceiver||'';$('pixBank').value=s.pixBank||'';$('logoUrl').value=s.logoUrl&&!String(s.logoUrl).startsWith('data:')?s.logoUrl:'';$('assistantMediaUrl').value=s.assistantMedia&&!String(s.assistantMedia).startsWith('data:')?s.assistantMedia:'';renderPreview('logoPreview',s.logoUrl,'image','Usando a logo atual ou padrão.');renderPreview('assistantMediaPreview',s.assistantMedia,inferType(s.assistantMedia,s.assistantMediaType),'Usando a mídia atual ou padrão.');}
  async function init(){if(!A.ready||!A.client)throw new Error('O Supabase não está configurado.');const {data:{session}}=await A.client.auth.getSession();if(!session)throw new Error('Faça login no painel do cliente antes de abrir esta página.');access=await A.myAccess();if(!access?.profile)throw new Error('Não foi possível identificar seu acesso.');if(!access.profile.attendant_enabled||!access.permissions?.['attendant.basic'])throw new Error('A edição dos dados essenciais não está liberada para este cliente.');const {data:att,error}=await A.client.from('attendant_profiles').select('public_settings').eq('user_id',access.profile.id).maybeSingle();if(error)throw error;loadFields(att?.public_settings||{});$('topStatus').textContent=(access.profile.full_name||access.profile.username)+' • envio para conferência';$('loadingView').classList.add('hidden');$('appView').classList.remove('hidden');setStep(1);await loadHistory();}
  async function loadHistory(){const {data,error}=await A.client.from('attendant_basic_requests').select('id,status,created_at,reviewed_at').eq('user_id',access.profile.id).order('created_at',{ascending:false}).limit(10);if(error)throw error;const list=data||[];$('historyList').innerHTML=list.length?list.map(r=>`<div class="history-item"><span class="badge ${esc(r.status)}">${r.status==='pending'?'Aguardando conferência':r.status==='applied'?'Aplicada':r.status==='rejected'?'Rejeitada':esc(r.status)}</span><div class="muted" style="font-size:12px;margin-top:6px">Enviado em ${new Date(r.created_at).toLocaleString('pt-BR')}${r.reviewed_at?' • analisado em '+new Date(r.reviewed_at).toLocaleString('pt-BR'):''}</div></div>`).join(''):'<div class="muted">Nenhum envio realizado ainda.</div>';}
  function isDataUrl(value){return /^data:[^;]+;base64,/i.test(String(value||''));}
  function extensionFor(type){const map={'image/png':'png','image/jpeg':'jpg','image/jpg':'jpg','image/webp':'webp','image/gif':'gif','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'};return map[String(type||'').toLowerCase()]||'bin';}
  function cleanSlug(value){return String(value||'atendente').toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'atendente';}
  async function uploadPayloadMedia(value,slot,max){if(!isDataUrl(value))return value;const response=await fetch(value);if(!response.ok)throw new Error('Não foi possível preparar o arquivo.');const blob=await response.blob();if(blob.size>max)throw new Error(slot+' ultrapassa o tamanho permitido.');const slug=cleanSlug(access?.attendant?.slug||access?.profile?.username||access.profile.id);const path=`${access.profile.id}/${slug}/${slot}-${Date.now()}.${extensionFor(blob.type)}`;const {error}=await A.client.storage.from(BUCKET).upload(path,blob,{contentType:blob.type||undefined,cacheControl:'31536000',upsert:false});if(error)throw error;const {data}=A.client.storage.from(BUCKET).getPublicUrl(path);const url=data?.publicUrl||data?.publicURL||'';if(!url)throw new Error('Não foi possível obter o link do arquivo.');return url;}
  async function submit(){$('submitBtn').disabled=true;$('formMsg').textContent='Enviando arquivos e dados...';try{const payload=validate();payload.logoUrl=await uploadPayloadMedia(payload.logoUrl,'logo',2*1024*1024);payload.assistantMedia=await uploadPayloadMedia(payload.assistantMedia,'atendente',5*1024*1024);const {error}=await A.client.from('attendant_basic_requests').insert({user_id:access.profile.id,payload,status:'pending'});if(error)throw error;A.toast('Dados enviados para conferência.');$('formMsg').textContent='Enviado com sucesso. A atendente atual continua funcionando até a aprovação.';setStep(1);await loadHistory();}catch(err){$('formMsg').textContent=err.message||'Não foi possível enviar.';}finally{$('submitBtn').disabled=false;}}
  $('logoUrl').addEventListener('input',()=>{const v=$('logoUrl').value.trim();if(v){media.logo=v;renderPreview('logoPreview',v,'image','');}else media.logo=null;});$('assistantMediaUrl').addEventListener('input',()=>{const v=$('assistantMediaUrl').value.trim();if(v){media.assistant=v;media.assistantType=inferType(v);renderPreview('assistantMediaPreview',v,media.assistantType,'');}else{media.assistant=null;media.assistantType=null;}});$('logoFile').addEventListener('change',async e=>{try{const r=await readMediaFile(e.target.files?.[0],'logo');if(!r)return;media.logo=r.value;$('logoUrl').value='';renderPreview('logoPreview',r.value,'image','');}catch(err){e.target.value='';A.toast(err.message,'error');}});$('assistantMediaFile').addEventListener('change',async e=>{try{const r=await readMediaFile(e.target.files?.[0],'assistant');if(!r)return;media.assistant=r.value;media.assistantType=r.type;$('assistantMediaUrl').value='';renderPreview('assistantMediaPreview',r.value,r.type,'');}catch(err){e.target.value='';A.toast(err.message,'error');}});$('removeLogo').onclick=()=>{media.logo='';$('logoUrl').value='';$('logoFile').value='';renderPreview('logoPreview','','image','Logo será removida após aprovação.');};$('removeAssistantMedia').onclick=()=>{media.assistant='';media.assistantType='';$('assistantMediaUrl').value='';$('assistantMediaFile').value='';renderPreview('assistantMediaPreview','','image','Mídia será removida após aprovação.');};$('nextBtn').onclick=()=>{try{validate();setStep(2);$('formMsg').textContent='';}catch(e){$('formMsg').textContent=e.message;}};$('backBtn').onclick=()=>setStep(1);$('submitBtn').onclick=submit;
  init().catch(e=>{$('loadingText').innerHTML=`${esc(e.message||String(e))}<br><br><a class="btn blue" href="geradores/">Voltar ao painel</a>`;});
})();
