(function(){
  'use strict';
  const A=window.JC_APP,$=id=>document.getElementById(id);const state={access:null,isAdmin:false,reports:[],clients:[],selectedUser:''};
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);}
  function dateTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR');}
  function text(v){if(v===null||v===undefined||v==='')return '—';if(Array.isArray(v))return v.join(', ');if(typeof v==='object')return JSON.stringify(v);return String(v);}
  function reportTitle(r){const p=r.payload||{};return p.name||p.customerName||p.service||p.plan||'Atendimento registrado';}
  function importantEntries(payload){const preferred=[['Nome','name'],['Interesse','service'],['Aparelho','device'],['Plano','plan'],['Quantidade','quantity'],['Pagamento','paymentMethod'],['Valor','finalPrice'],['Previsão','urgency'],['Modelo','boxOptionName'],['Parcelas','cardInstallments'],['Valor da parcela','cardInstallmentValue'],['Dúvidas','questions']];const used=new Set();const rows=[];preferred.forEach(([label,key])=>{if(payload[key]!==undefined&&payload[key]!==''&&payload[key]!==null){used.add(key);let value=payload[key];if(['finalPrice','basePrice','cardInstallmentValue'].includes(key)&&Number.isFinite(Number(value)))value=A.money(value);rows.push([label,text(value)]);}});Object.entries(payload).forEach(([key,value])=>{if(used.has(key)||['id','createdAt','created_at'].includes(key)||value===undefined||value===null||value==='')return;if(rows.length>=12)return;rows.push([key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase()),text(value)]);});return rows;}
  function filtered(){const q=$('searchInput').value.trim().toLowerCase();return state.reports.filter(r=>{if(state.isAdmin&&state.selectedUser&&r.user_id!==state.selectedUser)return false;if(!q)return true;return [r.owner_name,r.owner_username,r.attendant_slug,JSON.stringify(r.payload||{})].join(' ').toLowerCase().includes(q);});}
  function renderStats(list){$('statTotal').textContent=list.length;const today=new Date().toISOString().slice(0,10);$('statToday').textContent=list.filter(r=>String(r.created_at||'').slice(0,10)===today).length;$('statClients').textContent=new Set(list.map(r=>r.user_id)).size;}
  function render(){const list=filtered();renderStats(list);const box=$('reportsList');if(!list.length){box.innerHTML='<div class="empty">Nenhum relatório encontrado.</div>';return;}box.innerHTML=list.map(r=>{const rows=importantEntries(r.payload||{});return `<article class="report"><div class="report-head"><div><h3>${esc(reportTitle(r))}</h3><small>${esc(state.isAdmin?(r.owner_name||r.owner_username||r.attendant_slug):r.attendant_slug)} • ${esc(dateTime(r.created_at))}</small></div><div class="report-actions"><button class="btn red" data-delete="${esc(r.id)}">Excluir este relatório</button></div></div><div class="report-grid">${rows.map(([a,b])=>`<div><small>${esc(a)}</small><b>${esc(b)}</b></div>`).join('')}</div></article>`;}).join('');box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteOne(b.dataset.delete));}
  async function loadClients(){if(!state.isAdmin)return;const {data,error}=await A.client.from('profiles').select('id,username,full_name,role,attendant_profiles(slug)').in('role',['admin','client','test']).order('role',{ascending:true}).order('full_name');if(error)throw error;state.clients=(data||[]).filter(c=>Array.isArray(c.attendant_profiles)?c.attendant_profiles.length:Boolean(c.attendant_profiles));$('clientFilter').innerHTML='<option value="">Todos os clientes</option>'+state.clients.map(c=>`<option value="${esc(c.id)}">${c.role==='admin'?'Minha Atendente — ':''}${esc(c.full_name||c.username)}${c.role==='admin'?' (Administrador)':' — @'+esc(c.username)}</option>`).join('');const requested=new URLSearchParams(location.search).get('cliente')||'';if(requested&&state.clients.some(c=>c.id===requested)){$('clientFilter').value=requested;state.selectedUser=requested;}}
  async function loadReports(){const args={p_user_id:state.isAdmin?(state.selectedUser||null):null,p_limit:1000};const {data,error}=await A.client.rpc('list_attendant_reports',args);if(error)throw error;state.reports=data||[];render();}
  async function deleteOne(id){if(!confirm('Excluir somente este relatório?'))return;const {data,error}=await A.client.rpc('delete_attendant_report',{p_report_id:id});if(error)throw error;if(!data)throw new Error('Você não tem permissão para excluir este relatório.');state.reports=state.reports.filter(r=>r.id!==id);render();A.toast('Relatório excluído.');}
  async function clearClient(){const id=state.selectedUser;if(!id){A.toast('Escolha um cliente antes de limpar.','error');return;}const name=state.clients.find(c=>c.id===id)?.full_name||'este cliente';if(!confirm(`Apagar todos os relatórios de ${name}? Esta ação não pode ser desfeita.`))return;const {data,error}=await A.client.rpc('clear_attendant_reports',{p_user_id:id});if(error)throw error;A.toast(`${Number(data||0)} relatório(s) apagado(s).`);await loadReports();}
  async function clearAll(){if(!confirm('Apagar os relatórios de TODOS os clientes? Esta ação não pode ser desfeita.'))return;if(!confirm('Confirma novamente a limpeza geral de todos os relatórios?'))return;const {data,error}=await A.client.rpc('clear_attendant_reports',{p_user_id:null});if(error)throw error;A.toast(`${Number(data||0)} relatório(s) apagado(s).`);state.selectedUser='';$('clientFilter').value='';await loadReports();}
  async function init(){if(!A.ready||!A.client)throw new Error('O Supabase não está configurado.');const {data:{session}}=await A.client.auth.getSession();if(!session)throw new Error('Faça login no painel antes de abrir os relatórios.');state.access=await A.myAccess();if(!state.access?.profile)throw new Error('Não foi possível identificar seu acesso.');state.isAdmin=state.access.profile.role==='admin';if(!state.isAdmin&&!state.access.profile.attendant_enabled)throw new Error('Sua conta não possui uma atendente vinculada.');$('topStatus').textContent=state.isAdmin?'Administrador — relatórios de todos os clientes':(state.access.profile.full_name||state.access.profile.username)+' — somente seus relatórios';$('accessNotice').innerHTML=state.isAdmin?'Você pode visualizar todos os clientes, excluir um relatório, limpar um cliente inteiro ou limpar todos de uma vez.':'Você visualiza somente os relatórios da sua atendente e pode excluir um registro por vez. A limpeza em massa é exclusiva do administrador.';if(state.isAdmin){$('adminLink').classList.remove('hidden');$('backLink').classList.add('hidden');$('clientFilterField').classList.remove('hidden');$('adminDanger').classList.remove('hidden');await loadClients();}await loadReports();$('loadingView').classList.add('hidden');$('appView').classList.remove('hidden');}
  $('searchInput').oninput=render;$('clientFilter').onchange=async()=>{state.selectedUser=$('clientFilter').value;await loadReports().catch(e=>A.toast(e.message,'error'));};$('refreshBtn').onclick=()=>loadReports().then(()=>A.toast('Relatórios atualizados.')).catch(e=>A.toast(e.message,'error'));$('clearClientBtn').onclick=()=>clearClient().catch(e=>A.toast(e.message,'error'));$('clearAllBtn').onclick=()=>clearAll().catch(e=>A.toast(e.message,'error'));
  init().catch(e=>{$('loadingText').innerHTML=`${esc(e.message||String(e))}<br><br><small>Execute o arquivo SUPABASE-NOVO/08-RELATORIOS-ATENDENTE.sql se o módulo ainda não estiver instalado.</small><br><br><a class="btn blue" href="geradores/">Voltar ao painel</a>`;});
})();
