(function(){'use strict';
const A=window.JC_APP,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let access=null,packages=[],functions=[],officialModelsChecked=false;
const OFFICIAL_PACKAGE_SLUGS=['painel-completo-por-creditos','painel-completo-1000-creditos-launcher','ativador-16-completo-android-12','ativador-11-completo','acesse-aqui-codigo-download','pacote-apks-btv-stv-xplus-eaigo','recarga-launcher-1000-creditos','recarga-launcher-2500-creditos','recarga-launcher-5000-creditos','recarga-launcher-10000-creditos'];
function setView(ok){$('loginView').classList.toggle('hidden',ok);$('appView').classList.toggle('hidden',!ok);$('logoutBtn').classList.toggle('hidden',!ok)}
async function requireAdmin(){access=await A.requireAdmin();if(!access)throw new Error('Entre com uma conta de administrador.');setView(true);$('topStatus').textContent='Administrador: '+(access.profile.full_name||access.profile.username)}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function slug(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)}
function fnById(id){return functions.find(f=>f.id===id)}
function ids(list){return list.filter(id=>fnById(id))}
function idsPrefix(prefixes){return functions.filter(f=>prefixes.some(p=>String(f.id||'').startsWith(p))).map(f=>f.id)}
async function load(){const [p,f]=await Promise.all([A.client.from('jc_sales_packages').select('*').order('sort_order').order('name'),A.client.from('functions_catalog').select('id,name,group_name,active').eq('active',true).order('group_name').order('sort_order')]);if(p.error)throw p.error;if(f.error)throw f.error;packages=p.data||[];functions=f.data||[];await ensureOfficialModels();render();}
async function ensureOfficialModels(){if(officialModelsChecked||!functions.length)return;officialModelsChecked=true;const have=new Set((packages||[]).map(p=>p.slug));const missing=OFFICIAL_PACKAGE_SLUGS.filter(s=>!have.has(s));if(!missing.length)return;try{const models=modelPackages().filter(p=>missing.includes(p.slug));for(const m of models)await savePayload(m);A.toast('Modelos oficiais de Pacotes e Vendas criados automaticamente.');const {data,error}=await A.client.from('jc_sales_packages').select('*').order('sort_order').order('name');if(!error)packages=data||packages;}catch(e){console.warn('Modelos oficiais não criados automaticamente:',e?.message||e);A.toast('Não consegui criar os modelos automaticamente. Use o botão Recriar modelos oficiais.','error');}}
function render(){const q=String($('searchInput').value||'').toLowerCase();const showHidden=Boolean($('showHiddenPackages')?.checked);const rows=packages.filter(p=>(showHidden||p.status!=='hidden')&&(!q||[p.name,p.description,p.sale_message,...(p.function_ids||[])].join(' ').toLowerCase().includes(q)));$('packagesHost').innerHTML=rows.length?rows.map(p=>{const labels=(p.function_ids||[]).map(id=>functions.find(f=>f.id===id)?.name||id);const hidden=p.status==='hidden';return `<article class="package ${p.status==='active'?'':'inactive'}"><div class="package-head"><div><h3>${esc(p.name)}</h3><div class="badges"><span class="badge ${p.status==='active'?'green':'amber'}">${esc(hidden?'oculto':p.status)}</span><span class="badge">${esc(p.audience||'all')}</span></div></div></div><p class="muted">${esc(p.description||'Sem descrição.')}</p><div class="price"><div><small>Preço de venda</small><b>${money(p.price_brl)}</b></div><div><small>Créditos/função</small><b>${Number(p.credit_cost||0)} créditos</b></div></div><div class="included">${labels.length?labels.map(x=>`<span>✓ ${esc(x)}</span>`).join(''):'<span>Nenhuma função incluída</span>'}</div><div class="package-actions"><button class="btn blue" data-edit="${esc(p.id)}">Editar</button><button class="btn ${p.status==='active'?'amber':'green'}" data-toggle="${esc(p.id)}">${p.status==='active'?'Colocar em manutenção':'Ativar'}</button><button class="btn red" data-hide="${esc(p.id)}">${hidden?'Manter oculto':'Ocultar/arquivar'}</button><button class="btn red" data-delete="${esc(p.id)}">Excluir definitivo</button></div></article>`}).join(''):'<div class="empty" style="grid-column:1/-1">Nenhum pacote encontrado.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggle));document.querySelectorAll('[data-hide]').forEach(b=>b.onclick=()=>hidePackage(b.dataset.hide));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePackage(b.dataset.delete));}
function renderFunctions(selected=[]){const set=new Set(selected);const groups=new Map();functions.forEach(f=>{const g=f.group_name||'Outras';if(!groups.has(g))groups.set(g,[]);groups.get(g).push(f)});$('packageFunctions').innerHTML=[...groups].map(([g,list])=>`<div style="grid-column:1/-1;color:#8fdcff;font-size:11px;font-weight:900;margin-top:4px">${esc(g)}</div>${list.map(f=>`<label class="check"><input type="checkbox" data-package-function value="${esc(f.id)}" ${set.has(f.id)?'checked':''}><span><b>${esc(f.name)}</b><small>${esc(f.id)}</small></span></label>`).join('')}`).join('')}
function openEditor(id){const p=packages.find(x=>x.id===id)||{};$('packageId').value=p.id||'';$('packageName').value=p.name||'';$('packageSlug').value=p.slug||'';$('packageDescription').value=p.description||'';$('packagePrice').value=Number(p.price_brl||0);$('packageCreditCost').value=Number(p.credit_cost||0);$('packageProductKey').value=p.product_key||'geral';$('packageSort').value=Number(p.sort_order||100);$('packageAudience').value=p.audience||'all';$('packageStatus').value=p.status||'active';$('packageMessage').value=p.sale_message||'';$('packageModalTitle').textContent=p.id?'Editar pacote':'Novo pacote';renderFunctions(p.function_ids||[]);$('packageModal').classList.add('open')}
function close(){ $('packageModal').classList.remove('open') }
async function save(){const payload={id:$('packageId').value||null,name:$('packageName').value.trim(),slug:slug($('packageSlug').value||$('packageName').value),description:$('packageDescription').value.trim(),price_brl:Number($('packagePrice').value||0),credit_cost:Math.max(0,Math.floor(Number($('packageCreditCost').value||0))),product_key:slug($('packageProductKey').value)||'geral',sort_order:Math.floor(Number($('packageSort').value||100)),audience:$('packageAudience').value,status:$('packageStatus').value,sale_message:$('packageMessage').value.trim(),function_ids:[...document.querySelectorAll('[data-package-function]:checked')].map(x=>x.value)};if(!payload.name||!payload.slug)throw new Error('Informe nome e identificador.');const {data,error}=await A.client.rpc('jc_admin_save_sales_package',{p_payload:payload});if(error)throw error;A.toast(data?.message||'Pacote salvo.');close();await load()}
async function savePayload(payload){const {error}=await A.client.rpc('jc_admin_save_sales_package',{p_payload:payload});if(error)throw error;}
async function toggle(id){const p=packages.find(x=>x.id===id);if(!p)return;await savePayload({...p,status:p.status==='active'?'maintenance':'active'});await load()}
async function hidePackage(id){const p=packages.find(x=>x.id===id);if(!p)return;if(!confirm('Ocultar/arquivar este pacote? Ele sai da vitrine do cliente e fica guardado para conferência.'))return;try{await savePayload({...p,status:'hidden'});A.toast('Pacote ocultado.');}catch(e){await savePayload({...p,status:'maintenance'});A.toast('Não foi possível usar status oculto; pacote colocado em manutenção.');}await load()}
async function deletePackage(id){const p=packages.find(x=>x.id===id);if(!p)return;const ok=prompt('Para excluir definitivamente este pacote errado, digite EXCLUIR PACOTE.\nEssa ação remove da tabela de pacotes, mas não muda clientes nem permissões.');if(ok!=='EXCLUIR PACOTE')return;const {error}=await A.client.from('jc_sales_packages').delete().eq('id',id);if(error){A.toast('Não foi possível excluir direto; pacote foi ocultado para não aparecer ao cliente.','error');await savePayload({...p,status:'hidden'});}else A.toast('Pacote excluído.');await load()}
function modelPackages(){
  const configBase=ids(['config.open','config.access','config.generate_codes','config.copy_code','config.download_codes','config.download_apk','config.file_manager']);
  const act11=ids(['activator11.open','activator11.access','activator11.reset','activator11.generate','activator11.copy','activator11.generate_download','activator11.copy_download']);
  const act16=ids(['activator16.open','activator16.access','activator16.reset','activator16.generate','activator16.copy','activator16.generate_download','activator16.copy_download']);
  const apkPack=idsPrefix(['package.btv.','package.stv.','package.xplus.','package.eaigo.']);
  const launcher=idsPrefix(['launcher.']);
  const resellerLauncher=ids(['reseller.launcher.resell']);
  return [
    {slug:'painel-completo-por-creditos',name:'Painel completo por créditos',price_brl:650,credit_cost:1000,product_key:'geral',sort_order:9,description:'Pacote de referência para revendedor que comprou/recebeu o painel completo sem Launcher. Libera as funções disponíveis do painel por créditos, respeitando somente o que o ADM liberou para o revendedor. Launcher continua separada.',function_ids:[...new Set([...configBase,...act11,...act16,...apkPack])],sale_message:'Olá, tenho interesse no Painel completo por créditos. Quero negociar a liberação das funções do painel sem Launcher.'},
    {slug:'painel-completo-1000-creditos-launcher',name:'Painel completo + 1000 créditos Launcher',price_brl:700,credit_cost:1000,product_key:'launcher',sort_order:10,description:'Pacote máximo de referência: painel completo com funções comerciais liberadas, função Revender Launcher quando existir e 1000 créditos Launcher separados.',function_ids:[...new Set([...configBase,...act11,...act16,...apkPack,...launcher,...resellerLauncher])],sale_message:'Olá, tenho interesse no Painel completo + 1000 créditos Launcher. Quero negociar a liberação das funções restantes, a função Revender Launcher e os 1000 créditos Launcher separados.'},
    {slug:'ativador-16-completo-android-12',name:'16 dígitos completo + compatibilidade Android 12+',price_brl:400,product_key:'ativador16',sort_order:20,description:'Inclui .config/Acesse Aqui como base e o módulo 16 dígitos completo/Downloader, com foco em estabilidade Android 12+. Não inclui 11, Launcher, Revenda, IA/Painel ou créditos extras.',function_ids:[...new Set([...configBase,...act16])],sale_message:'Olá, tenho interesse no pacote 16 dígitos completo + compatibilidade Android 12+. Quero negociar a liberação manual das funções que ainda faltam.'},
    {slug:'ativador-11-completo',name:'Ativador 11 dígitos completo',price_brl:100,product_key:'ativador11',sort_order:30,description:'Pacote comercial para o módulo Ativador 11 dígitos, usando as funções já existentes do painel.',function_ids:[...new Set([...act11])],sale_message:'Olá, tenho interesse no Ativador 11 dígitos completo. Quero negociar a liberação manual.'},
    {slug:'acesse-aqui-codigo-download',name:'Acesse Aqui + código de download',price_brl:50,product_key:'config',sort_order:40,description:'Opção comercial para liberar/negociar Acesse Aqui e código de download, conforme permissões atuais.',function_ids:[...new Set(ids(['config.access','config.download_codes','activator11.generate_download','activator16.generate_download']))],sale_message:'Olá, tenho interesse no Acesse Aqui + código de download. Quero negociar a liberação manual.'},
    {slug:'pacote-apks-btv-stv-xplus-eaigo',name:'Pacote APKs BTV/STV/XPLUS/EAIGO',price_brl:100,product_key:'apks',sort_order:50,description:'Pacote comercial para opções de APKs já existentes no painel.',function_ids:[...new Set(apkPack)],sale_message:'Olá, tenho interesse no Pacote APKs BTV/STV/XPLUS/EAIGO. Quero negociar a liberação manual.'},
    {slug:'recarga-launcher-1000-creditos',name:'Recarga Launcher — 1.000 créditos',price_brl:50,credit_cost:1000,product_key:'launcher',sort_order:110,description:'Modelo de recarga comercial. O saldo deve ser conferido e lançado manualmente pelo ADM após pagamento.',function_ids:[],sale_message:'Olá, tenho interesse na recarga Launcher de 1.000 créditos.'},
    {slug:'recarga-launcher-2500-creditos',name:'Recarga Launcher — 2.500 créditos',price_brl:125,credit_cost:2500,product_key:'launcher',sort_order:120,description:'Modelo de recarga comercial. O saldo deve ser conferido e lançado manualmente pelo ADM após pagamento.',function_ids:[],sale_message:'Olá, tenho interesse na recarga Launcher de 2.500 créditos.'},
    {slug:'recarga-launcher-5000-creditos',name:'Recarga Launcher — 5.000 créditos',price_brl:250,credit_cost:5000,product_key:'launcher',sort_order:130,description:'Modelo de recarga comercial. O saldo deve ser conferido e lançado manualmente pelo ADM após pagamento.',function_ids:[],sale_message:'Olá, tenho interesse na recarga Launcher de 5.000 créditos.'},
    {slug:'recarga-launcher-10000-creditos',name:'Recarga Launcher — 10.000 créditos',price_brl:500,credit_cost:10000,product_key:'launcher',sort_order:140,description:'Modelo de recarga comercial de até 10.000 créditos por R$ 500,00. O saldo deve ser lançado manualmente pelo ADM após pagamento.',function_ids:[],sale_message:'Olá, tenho interesse na recarga Launcher de 10.000 créditos por R$ 500,00.'}
  ].map(x=>({id:packages.find(p=>p.slug===x.slug)?.id||null,slug:x.slug,name:x.name,description:x.description,price_brl:x.price_brl,credit_cost:Number(x.credit_cost||0),product_key:x.product_key,sort_order:x.sort_order,audience:'all',status:'active',sale_message:x.sale_message,function_ids:x.function_ids}));
}
async function seedModels(){if(!confirm('Recriar/atualizar os modelos oficiais em Pacotes e Vendas? Isso usa a tabela atual de pacotes e não libera nada automaticamente.'))return;const models=modelPackages();for(const p of models)await savePayload(p);A.toast(models.length+' modelos oficiais criados/atualizados.');await load();}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='Entrando...';try{await A.login($('loginUser').value,$('loginPass').value);await requireAdmin();await load();$('loginMsg').textContent=''}catch(err){$('loginMsg').textContent=err.message||'Falha no login.'}};
$('logoutBtn').onclick=async()=>{await A.client.auth.signOut();location.reload()};$('newPackageBtn').onclick=()=>openEditor();$('seedPackagesBtn').onclick=()=>seedModels().catch(e=>A.toast(e.message,'error'));$('reloadBtn').onclick=()=>load().catch(e=>A.toast(e.message,'error'));$('savePackageBtn').onclick=()=>save().catch(e=>A.toast(e.message,'error'));$('searchInput').oninput=render;if($('showHiddenPackages'))$('showHiddenPackages').onchange=render;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);$('packageModal').onclick=e=>{if(e.target===$('packageModal'))close()};$('packageName').oninput=()=>{if(!$('packageId').value)$('packageSlug').value=slug($('packageName').value)};
(async()=>{if(!A.ready)return;try{const {data:{session}}=await A.client.auth.getSession();if(session){await requireAdmin();await load()}}catch(e){await A.client.auth.signOut();setView(false);$('loginMsg').textContent=e.message}})();})();
